variables:
  NUGET_PACKAGES: $CI_PROJECT_DIR/packages/
  BUILD_IMAGE: eu.gcr.io/everybag-1273/dotnet/sdk-ci:5.0

stages:
  - build
  - publish

.base:
  image: $BUILD_IMAGE
  tags:
    - builder
  except:
    - tags

.publish:
  extends: .base
  stage: publish
  dependencies:
    - Build

Build:
  extends: .base
  stage: build
  artifacts:
    untracked: false
    when: on_success
    expire_in: '3 days'
    paths:
      - nugets/
  script:
    - v2-autobuild
    - v2-test-all
    - v2-publish-nuget src/Nyris.Extensions.AspNetCore.CacheControl

Release NuGets:
  extends: .publish
  only:
    - master
  script:
    - v2-push-nuget 'nugets/*.nupkg'

Unstable NuGets:
  extends: .publish
  when: manual
  except:
    - master
    - tags
  script:
    - v2-push-nuget 'nugets/*.nupkg'
